---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-svc
spec:
  selector:
    matchLabels:
      run: test-svc
  replicas: 1
  template:
    metadata:
      labels:
        run: test-svc
      annotations: {}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: test-svc
        image: "novella/svc-test:003"
        ports:
        - containerPort: 8080
        env:
          - name: "CONF_FILE_PATH"
            value: "/vault/secrets/test-svc.yaml"
          - name: "LOG_LEVEL"
            value: "debug"
          - name: "BIND_ADDR"
            value: "0.0.0.0:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  labels:
    run: test-svc
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: test-svc
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-svc-ingress
spec:
  rules:
  - host: test.129.16.123.117.nip.io
    http:
      paths:
      - backend:
          serviceName: test-svc
          servicePort: 8080
        path: /
  
